version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: haybici-minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    volumes: ["./data/minio:/data"]

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: haybici-mlflow
    ports: ["5000:5000"]
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns
    volumes: ["./mlruns:/mlruns", "./mlflow.db:/mlflow.db"]

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: haybici-api
    env_file: ["../.env"]
    ports: ["8080:8080"]
    volumes:
      - ../:/app
    depends_on: [mlflow, minio]
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8080 --reload
